# ZTR 压缩工具配置文件

# 压缩格式: 支持 "zip", "tar.gz", "7z"
format = "zip"

# 输出文件名 (可选，默认使用当前目录名)
# output_name = "my_archive"

# 忽略规则列表 (类似 .gitignore)
ignore = [".git/"]

# 指定忽略文件路径 (可选，默认使用 .gitignore)
ignore_file = "./.gitignore"
